services:
  instance:
    build:
      context: .
      dockerfile: Dockerfile
    develop:
      watch:
        - action: sync
          path: ./src
          target: /app/src
    ports:
      - "4200:4200"
    stdin_open: true
    tty: true
