FROM node:lts-alpine AS build

WORKDIR /app

COPY package*.json ./

RUN npm ci --only=production && \
    npm cache clean --force

FROM node:lts-alpine

WORKDIR /app

COPY --from=build /app/node_modules ./node_modules
COPY server.js ./

# Exposer le port du backend
EXPOSE 3000

# Définir les variables d'environnement
ENV NODE_ENV=production
ENV PORT=3000

# Commande pour démarrer le serveur
CMD ["node", "server.js"]
