name: Publish and deploy dev image
on:
  push:
    tags:
      - '!**'
  workflow_dispatch:
env:
  IMAGE_NAME: 'web/appquiz'
  REGISTRY_URL: ${{ secrets.HARBOR_URL }}

jobs:
  build-push:
    runs-on: gha-runners-smartweb
    strategy:
      matrix:
        include:
          - dockerfile: Dockerfile.backend
            image_name: web/appquiz-backend
          - dockerfile: Dockerfile.frontend
            image_name: web/appquiz-frontend
    steps:
      - name: Build tags
        run: |
          SHORT_SHA=$(echo ${{ github.sha }} | cut -c1-7)
          {
            echo 'IMAGE_TAGS<<EOF'
            echo '${{ env.REGISTRY_URL }}/${{ env.IMAGE_NAME }}:latest'
            echo '${{ env.REGISTRY_URL }}/${{ env.IMAGE_NAME }}:latest-'$SHORT_SHA
            echo EOF
          } >> $GITHUB_ENV
      - name: Build push and notify
        uses: IMIO/gha/build-push-notify@v5
        with:
          DOCKERFILE: ${{ matrix.dockerfile }}
          IMAGE_NAME: ${{ matrix.image_name }}
          IMAGE_TAGS: ${{ env.IMAGE_TAGS }}
          REGISTRY_URL: ${{ env.REGISTRY_URL}}
          REGISTRY_USERNAME: ${{ secrets.SMARTWEB_HARBOR_USERNAME }}
          REGISTRY_PASSWORD: ${{ secrets.SMARTWEB_HARBOR_PASSWORD }}
